/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tenant-audit-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TenantCheckController_boundCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tenant-audit-count-unbound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TenantCheckController_unboundCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/capability-check/enter-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CapabilityCheckController_enterResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/capability-check/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CapabilityCheckController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/capability-check/enter-result-unaudited": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CapabilityCheckController_enterResultUnaudited"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/capability-check/enter-result-forced-audit-failure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CapabilityCheckController_enterResultForcedAuditFailure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/capability-check/order-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CapabilityCheckController_orderCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/capability-check/audit-chain-valid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CapabilityCheckController_auditChainValid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PatientController_search"];
        put?: never;
        post: operations["PatientController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PatientController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patients/{id}/care-relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PatientController_assignClinician"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrderController_search"];
        put?: never;
        post: operations["OrderController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrderController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrderController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CatalogController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/test-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TestDefinitionController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reference-ranges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReferenceRangeController_list"];
        put?: never;
        post: operations["ReferenceRangeController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/specimens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpecimenController_search"];
        put?: never;
        post: operations["SpecimenController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/specimens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpecimenController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/specimens/{id}/label": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpecimenController_label"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/specimens/{id}/print": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SpecimenController_print"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordered-tests/{id}/results/{analyteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["ObservationController_draft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordered-tests/{id}/results/{analyteId}/draft-narrative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ObservationController_draftNarrative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordered-tests/{id}/results/{analyteId}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ObservationController_finalize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordered-tests/{id}/results/{analyteId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ObservationController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordered-tests/{id}/results/{analyteId}/prior": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ObservationController_prior"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordered-tests/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ObservationController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordered-tests/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReportController_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patients/{patientId}/cumulative-report/{analyteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CumulativeReportController_generate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patients/{patientId}/cumulative-report/{analyteId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CumulativeReportController_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/operational/tat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OperationalReportsController_tat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/operational/workload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OperationalReportsController_workload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/operational/rejection-rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OperationalReportsController_rejectionRate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/report-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportTemplateController_list"];
        put?: never;
        post: operations["ReportTemplateController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/report-templates/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReportTemplateController_createVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/report-templates/{id}/versions/{versionId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReportTemplateController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/worklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorklistController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/worklist/bulk-assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorklistController_bulkAssign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/worklist/bulk-cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorklistController_bulkCancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/control-lots/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ControlLotController_listResults"];
        put?: never;
        post: operations["ControlLotController_recordResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/control-lots/{id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ControlLotController_getChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/critical-notifications/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CriticalNotificationController_acknowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/critical-notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CriticalNotificationController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/qc-rule-violations/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["QcRuleViolationController_resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/qc-rule-violations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["QcRuleViolationController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/gateway/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GatewayIngestController_ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/interop/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InteropBridgeController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/interop/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InteropBridgeController_ingestOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/interop/observations/{id}/oru-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InteropBridgeController_getOruData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fhir/Observation/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FhirController_getObservation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portal/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PortalController_getResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflow-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowDefinitionController_list"];
        put?: never;
        post: operations["WorkflowDefinitionController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflow-definitions/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowDefinitionController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sla-breaches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SlaBreachController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clinician/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClinicianController_listPatients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clinician/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ClinicianController_createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clinician/patients/{patientId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClinicianController_getPatientResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clinician/critical-notifications/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ClinicianController_acknowledgeCritical"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OnboardingController_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PatientCreateDto: {
            nationalId?: string;
            firstName: string;
            middleName?: string;
            lastName: string;
            /** @enum {string} */
            sex: "M" | "F" | "U";
            /** Format: date */
            birthDate?: string;
        };
        PatientDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            mrn: string;
            nationalId: string | null;
            firstName: string;
            middleName: string | null;
            lastName: string;
            /** @enum {string} */
            sex: "M" | "F" | "U";
            /** Format: date */
            birthDate: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CareRelationshipCreateDto: {
            /** Format: uuid */
            clinicianUserId: string;
        };
        OrderCreateDto: {
            /** Format: uuid */
            patientId: string;
            testDefinitionIds?: string[];
            panelIds?: string[];
            /** @enum {string} */
            priority?: "routine" | "stat";
        };
        OrderDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            patientId: string;
            /** @enum {string} */
            status: "ordered" | "cancelled";
            /** @enum {string} */
            priority: "routine" | "stat";
            /** Format: date-time */
            createdAt: string;
            orderedTests: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                tenantId: string;
                /** Format: uuid */
                orderId: string;
                /** Format: uuid */
                testDefinitionId: string;
                /** @enum {string} */
                status: "ordered" | "collected" | "received" | "in_process" | "resulted" | "verified" | "reported" | "cancelled" | "rejected";
                /** Format: date-time */
                createdAt: string;
            }[];
            patient?: {
                firstName: string;
                lastName: string;
                mrn: string;
            };
        };
        CatalogDto_Output: {
            tests: {
                /** Format: uuid */
                id: string;
                code: string;
                displayName: string;
                analytes: {
                    /** Format: uuid */
                    id: string;
                    code: string;
                    display: string;
                    dataType: string;
                    unit: string | null;
                    /** Format: uuid */
                    unitId: string | null;
                }[];
            }[];
            panels: {
                /** Format: uuid */
                id: string;
                code: string;
                displayName: string;
                testDefinitionIds: string[];
            }[];
        };
        TestDefinitionCreateDto: {
            code: string;
            displayName: string;
            analyteIds: string[];
        };
        ReferenceRangeCreateDto: {
            /** Format: uuid */
            analyteId: string;
            /** Format: uuid */
            unitId: string;
            /** @enum {string} */
            sex?: "M" | "F";
            ageLowDays?: number;
            ageHighDays?: number;
            condition?: string;
            method?: string;
            specimenType?: string;
            population?: string;
            rangeType: string;
            low?: number;
            high?: number;
            textualRange?: string;
            interpretationWhenIn?: string;
            priority?: number;
            source?: string;
            /** Format: date-time */
            effectiveFrom?: string;
        };
        ReferenceRangeListDto_Output: {
            ranges: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                analyteId: string;
                analyteDisplay: string;
                /** Format: uuid */
                unitId: string;
                unitDisplay: string | null;
                sex: string | null;
                ageLowDays: number | null;
                ageHighDays: number | null;
                condition: string | null;
                method: string | null;
                specimenType: string | null;
                population: string | null;
                rangeType: string;
                low: number | null;
                high: number | null;
                textualRange: string | null;
                interpretationWhenIn: string | null;
                priority: number;
                source: string | null;
                /** Format: date-time */
                effectiveFrom: string;
                /** Format: date-time */
                effectiveTo: string | null;
                /** Format: date-time */
                createdAt: string;
            }[];
        };
        SpecimenCreateDto: {
            /** Format: uuid */
            orderId: string;
            specimenType: string;
            orderedTestIds?: string[];
            /** Format: date-time */
            collectedAt?: string;
            collectionContext?: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            rejectionReason?: "haemolysed" | "clotted" | "insufficient_volume" | "mislabelled" | "wrong_container" | "improper_temperature" | "expired";
        };
        SpecimenDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            accessionNumber: string;
            specimenType: string;
            /** Format: uuid */
            parentSpecimenId: string | null;
            /** @enum {string} */
            status: "collected" | "received" | "accessioned" | "in_process" | "completed" | "archived" | "disposed" | "rejected";
            /** @enum {string|null} */
            rejectionReason: "haemolysed" | "clotted" | "insufficient_volume" | "mislabelled" | "wrong_container" | "improper_temperature" | "expired" | null;
            collectionContext: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            collectedAt: string | null;
            /** Format: date-time */
            receivedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            fulfilledOrderedTestIds?: string[];
        };
        SpecimenLabelDto_Output: {
            accessionNumber: string;
            specimenType: string;
            /** Format: date-time */
            receivedAt: string | null;
            code128Svg: string;
            dataMatrixSvg: string;
        };
        ResultEntryDto: {
            /** @enum {string} */
            dataType: "quantity";
            valueNum: number;
        } | {
            /** @enum {string} */
            dataType: "coded";
            valueCode: string;
        } | {
            /** @enum {string} */
            dataType: "text";
            valueText: string;
        } | {
            /** @enum {string} */
            dataType: "ordinal";
            /** @enum {string} */
            valueCode: "none" | "1+" | "2+" | "3+";
            notes?: string;
            notesAiOriginated?: boolean;
            /** @enum {string} */
            notesAiDisposition?: "accepted" | "edited";
        };
        ObservationDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderedTestId: string;
            /** Format: uuid */
            analyteId: string;
            /** @enum {string} */
            dataType: "quantity" | "coded" | "text" | "ordinal";
            valueNum: number | null;
            valueCode: string | null;
            valueText: string | null;
            unit: string | null;
            refLow: number | null;
            refHigh: number | null;
            refCondition: string | null;
            refSource: string | null;
            flags: string[];
            /** @enum {string} */
            status: "registered" | "preliminary" | "verified";
            source: string;
            /** Format: date-time */
            producedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            verifierUserId: string | null;
            /** Format: date-time */
            verifiedAt: string | null;
            notes: string | null;
            notesAiOriginated: boolean;
            /** @enum {string|null} */
            notesAiDisposition: "accepted" | "edited" | null;
        };
        PriorObservationDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderedTestId: string;
            valueNum: number | null;
            valueCode: string | null;
            valueText: string | null;
            unit: string | null;
            flags: string[];
            /** Format: date-time */
            producedAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        TatReportDto_Output: {
            byPriority: {
                priority: string;
                count: number;
                meanMinutes: number;
                medianMinutes: number;
                withinTargetPct: number | null;
            }[];
            byTest: {
                /** Format: uuid */
                testDefinitionId: string;
                testDisplayName: string;
                count: number;
                meanMinutes: number;
                medianMinutes: number;
            }[];
        };
        WorkloadReportDto_Output: {
            entries: {
                userId: string;
                operatorCount: number;
                verifierCount: number;
            }[];
        };
        RejectionRateReportDto_Output: {
            totalSpecimens: number;
            rejectedTotal: number;
            byReason: {
                reason: string;
                count: number;
            }[];
        };
        ReportTemplateCreateDto__schema0: {
            and: components["schemas"]["ReportTemplateCreateDto__schema0"][];
        } | {
            or: components["schemas"]["ReportTemplateCreateDto__schema0"][];
        } | {
            not: components["schemas"]["ReportTemplateCreateDto__schema0"];
        } | {
            field: string;
            /** @enum {string} */
            op: "eq" | "neq" | "gt" | "gte" | "lt" | "lte" | "in" | "includes";
            value: unknown;
        };
        ReportTemplateCreateDto: {
            /** Format: uuid */
            testDefinitionId: string;
            definition: {
                sections: {
                    title: string;
                    fields: {
                        key: string;
                        label: string;
                        /** @enum {string} */
                        type: "numeric" | "coded" | "richText" | "table" | "referenceRangeDisplay";
                        /** Format: uuid */
                        analyteBinding?: string;
                        analyteBindings?: string[];
                        content?: string;
                        visibilityCondition?: components["schemas"]["ReportTemplateCreateDto__schema0"];
                    }[];
                }[];
            };
        };
        ReportTemplateVersionCreateDto__schema0: {
            and: components["schemas"]["ReportTemplateVersionCreateDto__schema0"][];
        } | {
            or: components["schemas"]["ReportTemplateVersionCreateDto__schema0"][];
        } | {
            not: components["schemas"]["ReportTemplateVersionCreateDto__schema0"];
        } | {
            field: string;
            /** @enum {string} */
            op: "eq" | "neq" | "gt" | "gte" | "lt" | "lte" | "in" | "includes";
            value: unknown;
        };
        ReportTemplateVersionCreateDto: {
            definition: {
                sections: {
                    title: string;
                    fields: {
                        key: string;
                        label: string;
                        /** @enum {string} */
                        type: "numeric" | "coded" | "richText" | "table" | "referenceRangeDisplay";
                        /** Format: uuid */
                        analyteBinding?: string;
                        analyteBindings?: string[];
                        content?: string;
                        visibilityCondition?: components["schemas"]["ReportTemplateVersionCreateDto__schema0"];
                    }[];
                }[];
            };
        };
        WorklistResponseDto_Output: {
            counts: {
                pending: number;
                inProgress: number;
                verified: number;
            };
            items: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                orderId: string;
                /** Format: uuid */
                testDefinitionId: string;
                testDisplayName: string;
                /** @enum {string} */
                status: "ordered" | "collected" | "received" | "in_process" | "resulted" | "verified" | "reported" | "cancelled" | "rejected";
                /** @enum {string} */
                priority: "routine" | "stat";
                patient: {
                    firstName: string;
                    lastName: string;
                    mrn: string;
                };
                /** Format: date-time */
                createdAt: string;
                ageMinutes: number;
                /** @enum {string} */
                slaStatus: "on_track" | "at_risk" | "overdue";
                /** Format: uuid */
                assignedUserId: string | null;
            }[];
        };
        WorklistBulkAssignDto: {
            orderedTestIds: string[];
            /** Format: uuid */
            assignedUserId: string | null;
        };
        WorklistBulkAssignResponseDto_Output: {
            updatedIds: string[];
            notFoundIds: string[];
        };
        WorklistBulkCancelDto: {
            orderedTestIds: string[];
        };
        WorklistBulkCancelResponseDto_Output: {
            cancelledIds: string[];
            ineligibleIds: string[];
        };
        QcObservationDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            controlLotId: string;
            /** Format: uuid */
            analyteId: string;
            /** @enum {string} */
            dataType: "quantity" | "coded" | "text" | "ordinal";
            valueNum: number | null;
            valueCode: string | null;
            valueText: string | null;
            unit: string | null;
            source: string;
            /** Format: date-time */
            producedAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        QcChartPointDto_Output: {
            /** Format: uuid */
            id: string;
            value: number;
            zScore: number;
            /** Format: date-time */
            producedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            violations: components["schemas"]["QcRuleViolationDto_Output"][];
        };
        QcRuleViolationDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            controlLotId: string;
            /** Format: uuid */
            observationId: string;
            /** @enum {string} */
            ruleCode: "1_2s" | "1_3s" | "2_2s" | "r_4s" | "4_1s" | "10x";
            /** @enum {string} */
            severity: "warning" | "rejection";
            /** Format: date-time */
            detectedAt: string;
            /** Format: date-time */
            resolvedAt: string | null;
            /** Format: uuid */
            resolvedByUserId: string | null;
        };
        QcChartDto_Output: {
            /** Format: uuid */
            controlLotId: string;
            /** Format: uuid */
            analyteId: string;
            level: string;
            targetMean: number;
            targetSd: number;
            points: components["schemas"]["QcChartPointDto_Output"][];
        };
        AcknowledgeDto: {
            readBack: string;
        };
        CriticalNotificationDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            observationId: string;
            /** @enum {string} */
            status: "pending" | "acknowledged" | "escalated";
            /** Format: date-time */
            createdAt: string;
            escalationLevel: number;
            /** Format: date-time */
            lastEscalatedAt: string | null;
            /** Format: date-time */
            acknowledgedAt: string | null;
            /** Format: uuid */
            acknowledgedByUserId: string | null;
            readBack: string | null;
        };
        QcRuleViolationListItemDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            controlLotId: string;
            /** Format: uuid */
            observationId: string;
            /** @enum {string} */
            ruleCode: "1_2s" | "1_3s" | "2_2s" | "r_4s" | "4_1s" | "10x";
            /** @enum {string} */
            severity: "warning" | "rejection";
            /** Format: date-time */
            detectedAt: string;
            /** Format: date-time */
            resolvedAt: string | null;
            /** Format: uuid */
            resolvedByUserId: string | null;
            /** Format: uuid */
            analyteId: string;
        };
        RawResultDto: {
            instrumentId: string;
            specimenId: string;
            analyte: string;
            runId: string;
            value: number | string;
            unit?: string;
            flag?: string;
            rawPayload: string;
        };
        InteropOrderIngestDto: {
            mrn: string;
            testCode: string;
            /** @enum {string} */
            priority?: "routine" | "stat";
            rawMessage: string;
        };
        AugmentedZodDto_Output: {
            patientMrn: string;
            patientFirstName: string;
            patientLastName: string;
            analyteCode: string;
            analyteDisplay: string;
            value: string;
            unit: string | null;
            refLow: number | null;
            refHigh: number | null;
            flags: string[];
            /** Format: date-time */
            verifiedAt: string;
        };
        PortalResultsResponseDto_Output: {
            analytes: {
                /** Format: uuid */
                analyteId: string;
                analyteDisplay: string;
                latest: {
                    /** Format: uuid */
                    observationId: string;
                    producedAt: string;
                    value: string;
                    unit: string;
                    flags: string[];
                    referenceRangeText: string;
                    isCritical: boolean;
                };
                trend: {
                    /** Format: uuid */
                    observationId: string;
                    producedAt: string;
                    value: string;
                    unit: string;
                    flags: string[];
                    referenceRangeText: string;
                    isCritical: boolean;
                }[];
            }[];
        };
        WorkflowDefinitionCreateDto__schema0: {
            and: components["schemas"]["WorkflowDefinitionCreateDto__schema0"][];
        } | {
            or: components["schemas"]["WorkflowDefinitionCreateDto__schema0"][];
        } | {
            not: components["schemas"]["WorkflowDefinitionCreateDto__schema0"];
        } | {
            field: string;
            /** @enum {string} */
            op: "eq" | "neq" | "gt" | "gte" | "lt" | "lte" | "in" | "includes";
            value: unknown;
        };
        WorkflowDefinitionCreateDto: {
            rules: {
                id: string;
                on: string;
                when: components["schemas"]["WorkflowDefinitionCreateDto__schema0"];
                do: {
                    command: string;
                } & {
                    [key: string]: unknown;
                };
                dryRun?: boolean;
            }[];
        };
        SlaBreachDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderedTestId: string;
            /** @enum {string} */
            priority: "routine" | "stat";
            targetMinutes: number;
            /** Format: date-time */
            breachedAt: string;
            /** @enum {string} */
            status: "pending" | "escalated" | "resolved";
            escalationLevel: number;
            /** Format: date-time */
            lastEscalatedAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        SignUpDto: {
            orgName: string;
            adminFirstName: string;
            adminLastName: string;
            /** Format: email */
            adminEmail: string;
            adminPassword: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantCheckController_boundCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantCheckController_unboundCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CapabilityCheckController_enterResult: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CapabilityCheckController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CapabilityCheckController_enterResultUnaudited: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CapabilityCheckController_enterResultForcedAuditFailure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CapabilityCheckController_orderCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CapabilityCheckController_auditChainValid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientController_search: {
        parameters: {
            query?: {
                mrn?: string;
                nationalId?: string;
                firstName?: string;
                lastName?: string;
                birthDate?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientDto_Output"][];
                };
            };
        };
    };
    PatientController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientDto_Output"];
                };
            };
        };
    };
    PatientController_assignClinician: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CareRelationshipCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_search: {
        parameters: {
            query?: {
                patientId?: string;
                status?: "ordered" | "cancelled";
                priority?: "routine" | "stat";
                createdFrom?: string;
                createdTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto_Output"][];
                };
            };
        };
    };
    OrderController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto_Output"];
                };
            };
        };
    };
    OrderController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogDto_Output"];
                };
            };
        };
    };
    TestDefinitionController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestDefinitionCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReferenceRangeController_list: {
        parameters: {
            query?: {
                analyteId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceRangeListDto_Output"];
                };
            };
        };
    };
    ReferenceRangeController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceRangeCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SpecimenController_search: {
        parameters: {
            query?: {
                orderId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenDto_Output"][];
                };
            };
        };
    };
    SpecimenController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecimenCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SpecimenController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenDto_Output"];
                };
            };
        };
    };
    SpecimenController_label: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenLabelDto_Output"];
                };
            };
        };
    };
    SpecimenController_print: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ObservationController_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                analyteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultEntryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationDto_Output"];
                };
            };
        };
    };
    ObservationController_draftNarrative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                analyteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ObservationController_finalize: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                analyteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultEntryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ObservationController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                analyteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ObservationController_prior: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                analyteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriorObservationDto_Output"][];
                };
            };
        };
    };
    ObservationController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationDto_Output"][];
                };
            };
        };
    };
    ReportController_generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CumulativeReportController_generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                analyteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CumulativeReportController_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                analyteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OperationalReportsController_tat: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TatReportDto_Output"];
                };
            };
        };
    };
    OperationalReportsController_workload: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkloadReportDto_Output"];
                };
            };
        };
    };
    OperationalReportsController_rejectionRate: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectionRateReportDto_Output"];
                };
            };
        };
    };
    ReportTemplateController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportTemplateController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportTemplateCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportTemplateController_createVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportTemplateVersionCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportTemplateController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorklistController_list: {
        parameters: {
            query?: {
                stage?: "pending" | "in_progress" | "verified";
                status?: "ordered" | "collected" | "received" | "in_process" | "resulted" | "verified" | "reported" | "cancelled" | "rejected";
                priority?: "routine" | "stat";
                createdFrom?: string;
                createdTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorklistResponseDto_Output"];
                };
            };
        };
    };
    WorklistController_bulkAssign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorklistBulkAssignDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorklistBulkAssignResponseDto_Output"];
                };
            };
        };
    };
    WorklistController_bulkCancel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorklistBulkCancelDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorklistBulkCancelResponseDto_Output"];
                };
            };
        };
    };
    ControlLotController_listResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QcObservationDto_Output"][];
                };
            };
        };
    };
    ControlLotController_recordResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultEntryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ControlLotController_getChart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QcChartDto_Output"];
                };
            };
        };
    };
    CriticalNotificationController_acknowledge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcknowledgeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CriticalNotificationController_list: {
        parameters: {
            query?: {
                status?: "pending" | "acknowledged" | "escalated";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriticalNotificationDto_Output"][];
                };
            };
        };
    };
    QcRuleViolationController_resolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    QcRuleViolationController_list: {
        parameters: {
            query?: {
                resolved?: "true" | "false";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QcRuleViolationListItemDto_Output"][];
                };
            };
        };
    };
    GatewayIngestController_ingest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RawResultDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InteropBridgeController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InteropBridgeController_ingestOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InteropOrderIngestDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InteropBridgeController_getOruData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AugmentedZodDto_Output"];
                };
            };
        };
    };
    FhirController_getObservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PortalController_getResults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalResultsResponseDto_Output"];
                };
            };
        };
    };
    WorkflowDefinitionController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowDefinitionController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowDefinitionCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowDefinitionController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SlaBreachController_list: {
        parameters: {
            query?: {
                status?: "pending" | "escalated" | "resolved";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlaBreachDto_Output"][];
                };
            };
        };
    };
    ClinicianController_listPatients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientDto_Output"][];
                };
            };
        };
    };
    ClinicianController_createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicianController_getPatientResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalResultsResponseDto_Output"];
                };
            };
        };
    };
    ClinicianController_acknowledgeCritical: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcknowledgeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OnboardingController_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
