/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tenant-audit-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TenantCheckController_boundCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tenant-audit-count-unbound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TenantCheckController_unboundCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/capability-check/enter-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CapabilityCheckController_enterResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/capability-check/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CapabilityCheckController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/capability-check/enter-result-unaudited": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CapabilityCheckController_enterResultUnaudited"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/capability-check/enter-result-forced-audit-failure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CapabilityCheckController_enterResultForcedAuditFailure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/capability-check/order-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CapabilityCheckController_orderCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/capability-check/audit-chain-valid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CapabilityCheckController_auditChainValid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PatientController_search"];
        put?: never;
        post: operations["PatientController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PatientController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrderController_search"];
        put?: never;
        post: operations["OrderController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrderController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrderController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CatalogController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/specimens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpecimenController_search"];
        put?: never;
        post: operations["SpecimenController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/specimens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpecimenController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/specimens/{id}/label": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SpecimenController_label"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/specimens/{id}/print": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SpecimenController_print"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordered-tests/{id}/results/{analyteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["ObservationController_draft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordered-tests/{id}/results/{analyteId}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ObservationController_finalize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordered-tests/{id}/results/{analyteId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ObservationController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordered-tests/{id}/results/{analyteId}/prior": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ObservationController_prior"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordered-tests/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ObservationController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PatientCreateDto: {
            nationalId?: string;
            firstName: string;
            middleName?: string;
            lastName: string;
            /** @enum {string} */
            sex: "M" | "F" | "U";
            /** Format: date */
            birthDate?: string;
        };
        PatientDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            mrn: string;
            nationalId: string | null;
            firstName: string;
            middleName: string | null;
            lastName: string;
            /** @enum {string} */
            sex: "M" | "F" | "U";
            /** Format: date */
            birthDate: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        OrderCreateDto: {
            /** Format: uuid */
            patientId: string;
            testDefinitionIds?: string[];
            panelIds?: string[];
            /** @enum {string} */
            priority?: "routine" | "stat";
        };
        OrderDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            patientId: string;
            /** @enum {string} */
            status: "ordered" | "cancelled";
            /** @enum {string} */
            priority: "routine" | "stat";
            /** Format: date-time */
            createdAt: string;
            orderedTests: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                tenantId: string;
                /** Format: uuid */
                orderId: string;
                /** Format: uuid */
                testDefinitionId: string;
                /** @enum {string} */
                status: "ordered" | "collected" | "received" | "in_process" | "resulted" | "verified" | "reported" | "cancelled" | "rejected";
                /** Format: date-time */
                createdAt: string;
            }[];
            patient?: {
                firstName: string;
                lastName: string;
                mrn: string;
            };
        };
        CatalogDto_Output: {
            tests: {
                /** Format: uuid */
                id: string;
                code: string;
                displayName: string;
                analytes: {
                    /** Format: uuid */
                    id: string;
                    code: string;
                    display: string;
                    dataType: string;
                    unit: string | null;
                }[];
            }[];
            panels: {
                /** Format: uuid */
                id: string;
                code: string;
                displayName: string;
                testDefinitionIds: string[];
            }[];
        };
        SpecimenCreateDto: {
            /** Format: uuid */
            orderId: string;
            specimenType: string;
            orderedTestIds?: string[];
            /** Format: date-time */
            collectedAt?: string;
            collectionContext?: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            rejectionReason?: "haemolysed" | "clotted" | "insufficient_volume" | "mislabelled" | "wrong_container" | "improper_temperature" | "expired";
        };
        SpecimenDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            accessionNumber: string;
            specimenType: string;
            /** Format: uuid */
            parentSpecimenId: string | null;
            /** @enum {string} */
            status: "collected" | "received" | "accessioned" | "in_process" | "completed" | "archived" | "disposed" | "rejected";
            /** @enum {string|null} */
            rejectionReason: "haemolysed" | "clotted" | "insufficient_volume" | "mislabelled" | "wrong_container" | "improper_temperature" | "expired" | null;
            collectionContext: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            collectedAt: string | null;
            /** Format: date-time */
            receivedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            fulfilledOrderedTestIds?: string[];
        };
        SpecimenLabelDto_Output: {
            accessionNumber: string;
            specimenType: string;
            /** Format: date-time */
            receivedAt: string | null;
            code128Svg: string;
            dataMatrixSvg: string;
        };
        ResultEntryDto: {
            /** @enum {string} */
            dataType: "quantity";
            valueNum: number;
        } | {
            /** @enum {string} */
            dataType: "coded";
            valueCode: string;
        } | {
            /** @enum {string} */
            dataType: "text";
            valueText: string;
        };
        ObservationDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderedTestId: string;
            /** Format: uuid */
            analyteId: string;
            /** @enum {string} */
            dataType: "quantity" | "coded" | "text";
            valueNum: number | null;
            valueCode: string | null;
            valueText: string | null;
            unit: string | null;
            refLow: number | null;
            refHigh: number | null;
            refCondition: string | null;
            refSource: string | null;
            flags: string[];
            /** @enum {string} */
            status: "registered" | "preliminary" | "verified";
            source: string;
            /** Format: date-time */
            producedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            verifierUserId: string | null;
            /** Format: date-time */
            verifiedAt: string | null;
        };
        PriorObservationDto_Output: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderedTestId: string;
            valueNum: number | null;
            valueCode: string | null;
            valueText: string | null;
            unit: string | null;
            flags: string[];
            /** Format: date-time */
            producedAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantCheckController_boundCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantCheckController_unboundCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CapabilityCheckController_enterResult: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CapabilityCheckController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CapabilityCheckController_enterResultUnaudited: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CapabilityCheckController_enterResultForcedAuditFailure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CapabilityCheckController_orderCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CapabilityCheckController_auditChainValid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientController_search: {
        parameters: {
            query?: {
                mrn?: string;
                nationalId?: string;
                firstName?: string;
                lastName?: string;
                birthDate?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientDto_Output"][];
                };
            };
        };
    };
    PatientController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientDto_Output"];
                };
            };
        };
    };
    OrderController_search: {
        parameters: {
            query?: {
                patientId?: string;
                status?: "ordered" | "cancelled";
                priority?: "routine" | "stat";
                createdFrom?: string;
                createdTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto_Output"][];
                };
            };
        };
    };
    OrderController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto_Output"];
                };
            };
        };
    };
    OrderController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogDto_Output"];
                };
            };
        };
    };
    SpecimenController_search: {
        parameters: {
            query?: {
                orderId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenDto_Output"][];
                };
            };
        };
    };
    SpecimenController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecimenCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SpecimenController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenDto_Output"];
                };
            };
        };
    };
    SpecimenController_label: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenLabelDto_Output"];
                };
            };
        };
    };
    SpecimenController_print: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ObservationController_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                analyteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultEntryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationDto_Output"];
                };
            };
        };
    };
    ObservationController_finalize: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                analyteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultEntryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ObservationController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                analyteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ObservationController_prior: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                analyteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriorObservationDto_Output"][];
                };
            };
        };
    };
    ObservationController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationDto_Output"][];
                };
            };
        };
    };
}
